# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-03 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='wxinfo',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='wxinfo',
            name='head',
            field=models.CharField(blank=True, max_length=300, verbose_name='head'),
        ),
        migrations.AlterField(
            model_name='wxinfo',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, verbose_name='nick name'),
        ),
        migrations.AlterField(
            model_name='wxinfo',
            name='openid',
            field=models.CharField(max_length=30, unique=True, verbose_name='openid'),
        ),
        migrations.AlterField(
            model_name='wxinfo',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='wxinfo',
            name='sex',
            field=models.CharField(blank=True, max_length=10, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='wxinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
