# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20190103_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='TWXOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=300, verbose_name='微信支付订单号')),
                ('time_end', models.CharField(blank=True, max_length=300, verbose_name='支付完成时间')),
                ('total_fee', models.CharField(blank=True, max_length=300, verbose_name='总金额')),
                ('openid', models.CharField(blank=True, max_length=300, verbose_name='付款人openid')),
                ('trade_type', models.CharField(blank=True, max_length=300, verbose_name='交易类型')),
                ('result_code', models.CharField(blank=True, max_length=300, verbose_name='业务结果')),
                ('body', models.CharField(blank=True, max_length=300, verbose_name='实际商品名称')),
                ('detail', models.TextField(blank=True, verbose_name='详细')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='记录创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='记录最后修改时间')),
                ('pay', models.CharField(blank=True, max_length=100, verbose_name='支付情况')),
                ('confirmed', models.BooleanField(default=False, verbose_name='是否确认')),
            ],
        ),
    ]
