# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20190427_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxinfo',
            name='sex',
            field=models.CharField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女')], max_length=10, verbose_name='sex'),
        ),
    ]
