# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20190427_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='twxorder',
            name='no',
            field=models.CharField(blank=True, max_length=300, verbose_name='内部微信订单号'),
        ),
    ]
