# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.order_key


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_twxorder_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twxorder',
            name='no',
            field=models.CharField(default=helpers.director.model_func.order_key.date_shortuuid, max_length=30, unique=True, verbose_name='内部微信订单号'),
        ),
    ]
