# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-09 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0007_auto_20190509_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='wxinfo',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='wxinfo',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='wxinfo',
            name='sex',
            field=models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
    ]
