# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-01 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_auto_20190509_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='手机号码'),
        ),
    ]
