# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-22 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0009_wxinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxinfo',
            name='appid',
            field=models.CharField(blank=True, max_length=30, verbose_name='Appid'),
        ),
        migrations.AddField(
            model_name='wxinfo',
            name='unionid',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='openid'),
        ),
        migrations.AlterField(
            model_name='wxinfo',
            name='openid',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='openid'),
        ),
    ]
