# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-22 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0010_auto_20210522_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxinfo',
            name='openid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='openid'),
        ),
        migrations.AddIndex(
            model_name='wxinfo',
            index=models.Index(fields=['openid'], name='wechat_wxin_openid_71c080_idx'),
        ),
    ]
