# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-24 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0011_auto_20210522_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxinfo',
            name='session_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='session_key'),
        ),
    ]
